### ISSUE TITLE
Licence is ambiguous

### ISSUE THREAD

**Issue by robinpaulson** [AdamWhitcroft/climacons#6]
This part:
"You are free to use any of the Climacons Icons (the "icons") in any personal or commercial work"

Appears contradictory to:
"Do not redistribute"

If I include climacons in a work, any use or viewing of that work will necessarily involve redistributing it (downloading, including software which uses them in a repository, using on a website, printing and giving out fliers). I'd like to use the icons, but can't for this reason. Would you consider adopting an existing licence/convention, such as CC, or even PD?

I ask because we are considering using Climacons in Forecastie, a weather app for Android and derivatives:
https://github.com/martykan/forecastie

**Comment by AdamWhitcroft** [comment]
Hey there, that part of the license covers websites taking the entire icon package, uploading it and distributing it (making money either from paid downloads of the kit, or by serving ads on their site). Using the icons as part of a design or app is cool.

Sorry for the delayed response, and thanks for using them!
